### ISSUE TITLE
Profiler can give the user extra info

### ISSUE THREAD

**Issue by argenisleon** [ironmussa/Optimus#632]
Profiler can detect at the moment:

* String
* Integer
* Decimal
* Boolean
* Array
* Date/Time

If a column is String it can give the user extra info like:
* IP Address
* URL
* Phone Number
* Email Address
* Credit Card
* Zip Code

Also a dict/json could be detected.

**Comment by arpit1997** [comment]
@argenisleon if you haven't started working on it then can I take this issue?

**Comment by argenisleon** [comment]
@arpit1997 go ahead. Please let me know if you need any help with this.

**Comment by arpit1997** [comment]
Thank you. I will surely ask if I need any help. I Will try to complete it
this weekend.

**Comment by arpit1997** [comment]
@argenisleon Running a bit late on this issue. I will try it by tuesday. Got the basic stuff figured out.

**Comment by arpit1997** [comment]
I will have to look into it once because I have never tested performance of
using dataframes vs RDD. Pickling might not be a big issue.

I have a couple of datasets. I can test on them and let you know what
I find.

**Comment by arpit1997** [comment]
I read upon this, Seems to be a good performance gain in Dataframes. Maybe we can try Datasets as well with RDDs to implement this? I am assuming data will be structured when we are calculating Histograms and Frequency. 

> But I am relaying more and more on them because it seems to scale better with big dataset for operations like frequency and histograms

Was there any observation or numbers you saw? Because seems like Dataframes are performant because of serialization process mentioned [here](https://data-flair.training/blogs/apache-spark-rdd-vs-dataframe-vs-dataset/)

**Comment by arpit1997** [comment]
@argenisleon Just tested this. Yeah its a significant improvement. Will you be replacing all of the methods which has similar behavior?

**Comment by argenisleon** [comment]
@arpit1997 new improvements for the profiler are now in master. Are you willing to keep working on this issue?

**Comment by arpit1997** [comment]
Yeah I am working on this. I will try to finish this up today.
